#! /usr/bin/python
import os

path = '/test/remove/'

cmd_body = 'mkdir '

list_option_INPUT = ['A','B','C']

for idx, option in enumerate(list_option_INPUT):
	for j in range (1, 2):
		cmd = cmd_body + path + option + str(j)
		print cmd
		os.system(cmd)
		cmd = cmd_body + path + option + str(j) + '/L'
		print cmd
		os.system(cmd)
		cmd = cmd_body + path + option + str(j) + '/R'
		print cmd
		os.system(cmd)
